# Generated by Django 3.0.5 on 2020-08-11 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20200811_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='logoutdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='logouttime',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=40),
        ),
    ]
