# Generated by Django 3.0.5 on 2020-08-13 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='loggedIn',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
