# Generated by Django 3.0.5 on 2020-08-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_employee_loggedin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='loggedIn',
            field=models.BooleanField(default=False),
        ),
    ]
