# Generated by Django 3.0.5 on 2020-08-13 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20200813_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='numMins',
            field=models.TimeField(),
            preserve_default=False,
        ),
    ]
