# Generated by Django 3.0.5 on 2020-08-13 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20200813_1014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='logindate',
            new_name='login',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='logoutdate',
            new_name='logout',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='logintime',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='logouttime',
        ),
    ]
