# Generated by Django 3.0.5 on 2020-08-13 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20200813_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='numMins',
        ),
    ]
